### ISSUE TITLE
Same name vm in other vcenter

### ISSUE THREAD

**Issue by MalfuncEddie** [synackray/vcenter-netbox-sync#93]
# Steps to Reproduce
1. Have the same VM in 2 different vcenters (in this case a template server that you roll out)
2. run the script
3. VM is "updated" twice (once for cluster A and once for cluster B

### Expected Behavior
The vm should be create two times, one in each cluster.

### Observed Behavior
When the script searches if a vm exists it finds the VM of CLUSTER B and changes is to CLUSTER A. When the script is processing CLUSTER B and it finds the same VM the VM is updated from CLUSTER A to B

**Comment by synackray** [comment]
Hello, @MalfuncEddie.

Thanks for the report. You are indeed correct we should only update the VM relevant to the vCenter it was detected on originally. I'll work on improving this behavior. Thanks for the report!

**Comment by synackray** [comment]
I have merged this into `develop`. Thanks!

**Comment by MalfuncEddie** [comment]
Hi,

I juist checkt the develop branch te see the fix. but it looks like the problem is still there.
The vm is create in the last cluster but it has the tags "Vcenter A" and "Vcenter B".

**Comment by synackray** [comment]
@MalfuncEddie I am requesting the resources to test this again. Was the sync done in an already populated NetBox instance? I had to remove the second vCenter tag from the existing VM object as it had already been synced that way and I didn't see a duplication on a fresh sync, but I am going to fully retest this on my side. Thanks!

**Comment by MalfuncEddie** [comment]
I'll clean my setup and run the sync again. results tomorrow :)

**Comment by MalfuncEddie** [comment]
Hi,

run.py -c 
Did a check an there were no vm/ tag/ ...

ran run.py again:
same result
vm gets created
vm get updated 
run it again
vm get updated 

the diff shows 
update 1
{
    "cluster": 23,
    "platform": 28
}
to 
{
    "cluster": 29,
    "platform": 1
}
update 2:
{
    "cluster": 29,
    "platform": 1
}
to 
{
    "cluster": 23,
    "platform": 28
}

**Comment by MalfuncEddie** [comment]
and the vm has 2 vcenter tags

**Comment by bb-Ricardo** [comment]
I didn't try it myself but can you have two virtual machines with the same name in netbox?

**Comment by gstorme** [comment]
No, VM name is unique

**Comment by bb-Ricardo** [comment]
Id and name are the primary keys. Then the only solution would be to rename both VMs in netbox with their cluster name as suffix.

**Comment by MalfuncEddie** [comment]
Hi,

This could be solved by adding a custom field UUID and using that as the
primary key.
In either case I've written a custom script that does juist that since I
also had the same cluster names in different vcenters :( .

kind regards

**Comment by bb-Ricardo** [comment]
I was thinking the same.

How did you name your clusters then?
Vcenter name as prefix?

**Comment by MalfuncEddie** [comment]
Yes I did

**Comment by bb-Ricardo** [comment]
Just stumbled across this issue. VM and Device names are NOT unique. Here a long discussion on this topic: https://github.com/netbox-community/netbox/issues/2669
